### ISSUE TITLE
Is this actually limited to samd51?

### ISSUE THREAD

**Issue by BlinkyStitt** [smart-leds-rs/ws2812-nop-samd51#2]
I am looking at the code and it looks like this should work on anything that uses `cortex-m = "~0.5"`. Is that right? Should this repo have a more general name?

**Comment by sajattack** [comment]
It's limited to anything with the same clock speed I believe.

**Comment by david-sawatzke** [comment]
More specifically, it'll work on anything where the timings, that are determined by the combination of hal-overhead and clockspeed, are close enough. But this is highly dependent on how the hal works, so this crate might be changed in case new atsamd-hal versions have different performance characteristics and other devices could fall out of the "working" range.

**Comment by BlinkyStitt** [comment]
Thanks for the explanation!
